"""empty message

Revision ID: 303072a83689
Revises: 
Create Date: 2017-11-23 20:52:24.119406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '303072a83689'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Contest',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('leaderboard',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('Questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_name', sa.String(length=20), nullable=False),
    sa.Column('ans_name', sa.String(length=20), nullable=False),
    sa.Column('test_name', sa.String(length=20), nullable=False),
    sa.Column('contest_na', sa.String(length=100), nullable=True),
    sa.Column('marks', sa.Integer(), nullable=False),
    sa.Column('edi_name', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['contest_na'], ['Contest.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solved',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('per', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['per'], ['leaderboard.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solved')
    op.drop_table('Questions')
    op.drop_table('leaderboard')
    op.drop_table('Contest')
    # ### end Alembic commands ###
